  resources:
    - name: mygitAppRepo
      type: GitRepo
      configuration:
          gitProvider: AnupsGitHub
          path: anupteal/quickstart-jfrog-artifactory
          branches:
             include: 7.11.2
  pipelines:
     - name: anup_taskcat_testing
       configuration:
         environmentVariables:
            readOnly:
               MY_MESSAGE: '"Hello World!"'

       steps:
         - name: step_1
           type: Bash
           configuration:
              inputResources:
                - name: mygitAppRepo
           execution:
              onExecute:
                - echo $MY_MESSAGE
                - echo "Running $pipeline_name | $step_name on node ID $step_node_id"
                - sudo pip3 install taskcat
