  resources:
    - name: mygitAppRepo
      type: GitRepo
      configuration:
          gitProvider: AnupsGitHub
          path: anupteal/quickstart-jfrog-artifactory
          branches:
             include: 7.11.2
  pipelines:
     - name: anup_taskcat_testing
       configuration:
         environmentVariables:
            readOnly:
               MY_MESSAGE: '"Hello World!"'
               aws_access_key_id: ${int_anupgeneric_aws_access_key_id}
               aws_secret_access_key: ${int_anupgeneric_aws_secret_access_key}
               region: "us-east-2"

       steps:
         - name: step_1
           type: Bash
           configuration:
              runtime:
                 type: image
                 image:
                   custom:
                     name: partnership-public-images.jfrog.io/cft/taskcat
                     tag: "1"
                     registry: anupdocker
              inputResources:
                   - name: mygitAppRepo
           execution:
              onExecute:
                - echo $aws_access_key_id
                - echo "Running $pipeline_name | $step_name on node ID $step_node_id"
                - taskcat --version
                - ls dependencyState/resources/mygitAppRepo/submodules/quickstart-aws-vpc/templates/aws-vpc.template
                - ls dependencyState/resources/mygitAppRepo/submodules/quickstart-aws-vpc/
                - cd dependencyState/resources/mygitAppRepo; taskcat test run -n -l
                - ls /var/opt/jfrog/pipelines/data/anup_taskcat_testing/workspace
