  resources:
    - name: mygitAppRepo
      type: GitRepo
      configuration:
          gitProvider: AnupsGitHub
          path: anupteal/quickstart-jfrog-artifactory
          branches:
             include: 7.11.2
  pipelines:
     - name: anup_taskcat_testing
       configuration:
         environmentVariables:
            readOnly:
               region: "us-east-2"
        

       steps:
         - name: Execute_taskcat
           type: Bash
           configuration:
              runtime:
                 type: image
                 image:
                   custom:
                     name: partnership-public-images.jfrog.io/cft/taskcat
                     tag: "1"
                     registry: anupdocker
              inputResources:
                   - name: mygitAppRepo
              integrations:
                   - name: anupgeneric
               

           execution:
              onExecute:
                - echo $int_anupgeneric_accesskey $int_anupgeneric_secretkey 
                - export AWS_ACCESS_KEY_ID=$int_anupgeneric_accesskey
                - export AWS_SECRET_ACCESS_KEY=$int_anupgeneric_secretkey
                - export AWS_DEFAULT_REGION=us-west-2
                - taskcat --version
                - git --version
                - cd dependencyState/resources/mygitAppRepo/; pwd; git submodule init; git submodule update --remote --recursive; while [ ! -f submodules/quickstart-aws-vpc/templates/aws-vpc.template  ]; do sleep 2 ; done
                - taskcat test run -n -l
               
