  resources:
    - name: mygitAppRepo
      type: GitRepo
      configuration:
          gitProvider: AnupsGitHub
          path: anupteal/quickstart-jfrog-artifactory
          branches:
             include: 7.11.2
  pipelines:
     - name: anup_taskcat_testing
       configuration:
         environmentVariables:
            readOnly:
               ACCESS_KEY: ${int_anupgeneric_accesskey}
               SECRET_KEY: ${int_anupgeneric_secretkey}
               region: "us-east-2"
        

       steps:
         - name: Execute_taskcat
           type: Bash
           configuration:
              runtime:
                 type: image
                 image:
                   custom:
                     name: partnership-public-images.jfrog.io/cft/taskcat
                     tag: "1"
                     registry: anupdocker
              integrations:
                   - name: anupgeneric
                   - name: AnupsAWS
              inputResources:
                   - name: mygitAppRepo
           execution:
              onExecute:
                - echo $int_anupgeneric_accesskey $int_anupgeneric_secretkey
                - export AWS_ACCESS_KEY_ID=$ACCESS_KEY
                - export AWS_SECRET_ACCESS_KEY=$SECRET_KEY
                - export AWS_DEFAULT_REGION=us-west-2
                - taskcat --version
                - git --version
                - cd dependencyState/resources/mygitAppRepo/submodules; pwd; rm -rf quickstart-aws-vpc; git clone https://github.com/aws-quickstart/quickstart-aws-vpc.git;  while [ ! -f quickstart-aws-vpc/templates/aws-vpc.template  ]; do sleep 2 ; done
                - rm -rf quickstart-linux-bastion; git clone https://github.com/aws-quickstart/quickstart-linux-bastion.git;  while [ ! -f quickstart-linux-bastion/templates/linux-bastion.template  ]; do sleep 2 ; done
                - cd ../; pwd
                - echo "taskcat test run -n -l"
               
