  resources:
    - name: mygitAppRepo
      type: GitRepo
      configuration:
          gitProvider: AnupsGitHub
          path: jfrogtw/jfrog-pipelines-hw
          branches:
             include: master
  pipelines:
     - name: pipeline_hello_world
       configuration:
         environmentVariables:
            readOnly:
               MY_MESSAGE: '"Hello World!"'

       steps:
         - name: step_1
           type: Bash
           configuration:
              inputResources:
                - name: myAppRepo
           execution:
              onExecute:
                - echo $MY_MESSAGE
                - echo "Running $pipeline_name | $step_name on node ID $step_node_id"
